sudo: required
dist: trusty
language: java
cache:
  directories:
  - "~/.m2"
jdk:
- oraclejdk11
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
install:
- 
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
    - almaslvl@gmail.com
    on_success: change
    on_failure: always
    on_start: never